/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clevertec.course.gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        StringUtils classUnderTest = new StringUtils();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.isPositiveNumber(String.valueOf(1)));
    }
}
