/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clevertec.course.gradle;

import static org.apache.commons.lang3.StringUtils.isNumeric;

public class StringUtils {
    public boolean isPositiveNumber(String str) {
        return isNumeric(str) && (Integer.parseInt(str) > 0);
    }
}
